# Generated by Django 5.0.6 on 2024-09-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='room_booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mob', models.CharField(max_length=10)),
                ('sharing_number', models.IntegerField(unique=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_number', models.IntegerField()),
                ('bed_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_number', models.IntegerField(unique=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mob', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=8)),
                ('rpwd', models.CharField(max_length=8)),
                ('img', models.ImageField(upload_to='images/')),
                ('doc', models.FileField(upload_to='documents/')),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
